<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reCAPTCHA_recaptcha-checkbox-border</name>
   <tag></tag>
   <elementGuidId>b49ab547-336a-453c-8dd5-f1663be9e431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.recaptcha-checkbox-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='recaptcha-anchor']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd78455b-fc45-4947-b046-300fc5ca9ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recaptcha-checkbox-border</value>
      <webElementGuid>e16079c6-2345-412f-8cca-72a0381f0fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>21e0e29d-b4e7-4a05-9b53-fd2ced18675c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor&quot;)/div[@class=&quot;recaptcha-checkbox-border&quot;]</value>
      <webElementGuid>ec49d7b9-aa16-45cf-af71-407fb661320a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Register/Register Without Fill Last Name/Page_DEMOQA/iframe_Password_a-f8snekj7sn2x</value>
      <webElementGuid>30dc9a3f-7539-4838-a56a-60530c72a88d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div</value>
      <webElementGuid>55d59bbd-6848-4179-9917-34869f043d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>5f89c8d6-627f-49d3-ace8-0ba1ad31846d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
