<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Passwords must have at least one non alph_e3847b</name>
   <tag></tag>
   <elementGuidId>9e36b3a0-9349-41ba-9056-2ceec154597d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dede7c77-9fa4-403e-9db0-27f648af50af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>656f98e2-2174-4a5d-bbd9-f56a0c6206e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>c9cba926-2bd6-4419-bdbd-09d0f1a3b98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passwords must have at least one non alphanumeric character, one digit ('0'-'9'), one uppercase ('A'-'Z'), one lowercase ('a'-'z'), one special character and Password must be eight characters or longer.</value>
      <webElementGuid>0f1a90a4-ffd7-42a9-a23b-c41a7dba890e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name&quot;)</value>
      <webElementGuid>71095601-7f0e-43f3-9b00-83d7f8d1b1c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='name']</value>
      <webElementGuid>3f350a90-333b-4ed7-881a-166150a2d091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/p</value>
      <webElementGuid>1ef28478-4f8a-44bc-8de2-4abdb549e146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Login'])[1]/following::p[1]</value>
      <webElementGuid>8ea3f3d9-0025-4473-9396-c5cba400dab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/following::p[1]</value>
      <webElementGuid>0bdd25f8-0982-44fc-9eb5-1d1f25f51f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>6752a6e7-a53b-4c46-83db-c4697afe1eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'name', '&quot;', ')')])[1]/preceding::p[1]</value>
      <webElementGuid>53f4e62b-6369-444b-8f51-017981436639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>4c983c6a-4ac3-4a35-90f9-3c83e10c83e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'name' and (text() = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;) or . = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;))]</value>
      <webElementGuid>95507b04-fa73-49d4-a503-f17c2d852ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
